### ISSUE TITLE
wasm SharedArrayBuffer is not defined

### ISSUE THREAD

**Issue by duanyuanyuan01** [fraunhoferhhi/vvdec#172]

**Comment by K-os** [comment]
I have no idea what you want to tell us. Please give enough information to reproduce the issue, otherwise I will close it.

**Comment by duanyuanyuan01** [comment]
> I have no idea what you want to tell us. Please give enough information to reproduce the issue, otherwise I will close it.

![image](https://github.com/fraunhoferhhi/vvdec/assets/156426850/92ce1ec8-7a5f-4bc5-a51b-c0405b61a6e2)

Browser prohibits the use of SharedArrayBuffer

**Comment by adamjw24** [comment]
A proper bug report will require:
* OS version
* browser version
* cross-check on another browser
* any additional info

Are you using a company PC browser that might have some custom restrictions? Like, there's a screen-shot that I cannot even read and no info on how to reproduce....

All that said, the most probable resolution to your issue is that the decoder is incompatible with your browser. It's all standard WASM technology as far as I know. That's why we also don't support Safari.

**Comment by adamjw24** [comment]
Also, you are using a custom application. Did you try 1:1 to use our setup provided in https://github.com/fraunhoferhhi/vvdecWebPlayer? That did work for me last I time tried.

**Comment by K-os** [comment]
You probably did not set the correct HTTP-headers in the webserver to use SharedArrayBuffer. You need to set `Cross-Origin-Opener-Policy: same-origin` and `Cross-Origin-Embedder-Policy: require-corp`. 
See here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer

**Comment by K-os** [comment]
I guess the problem has been solved.
