### ISSUE TITLE
Any plan to integrate vvdec into ffmepg?

### ISSUE THREAD

**Issue by meetviolet** [fraunhoferhhi/vvdec#203]
Is there any plan to integrate vvdec into ffmepg?

**Comment by adamjw24** [comment]
No. FFmpeg has its own VVC decoder.

**Comment by birdie-github** [comment]
There's a patchset to enable vvdec support in ffmpeg up to version 6.1 but it's no longer updated.

**Comment by K-os** [comment]
> There's a patchset to enable vvdec support in ffmpeg up to version 6.1 but it's no longer updated.

This is only partially correct. Yes, there is a patchset, that has been submitted to the FFmpeg, but it was rejected, because they prefer the internal decoder implementation. So there is no point in resubmitting updated versions.

But we do have an updated version of the patchset linked in our wiki, which should apply against the latest versions of the FFmpeg code base. It's all documented here: https://github.com/fraunhoferhhi/vvdec/wiki/Integration-in-FFmpeg

**Comment by birdie-github** [comment]
> but it was rejected

For two reasons:
1. It implemented all the VVC related data structures (now redundant)
2. FFMpeg wanted to have something native that they have full control and understanding of

Considering item 1 is now fully implemented, I'm pretty sure the new much lighter patch to integrate vvdec will be accepted. Also, the new patch will be a lot easier to maintain.

Sadly Thomas Siedel from Spin Digital hasn't returned my emails.
