### ISSUE TITLE
Which is the pixel format of the yuv output?

### ISSUE THREAD

**Issue by rafael2k** [fraunhoferhhi/vvdec#4]
Which is the pixel format of the yuv output?
I'm trying to convert with ffmpeg to a format I can read, but I don't know which format to choose (yuv422p did not work, yuv420p obviously not too).

**Comment by rafael2k** [comment]
Answering myself... yuv420p10le

**Comment by moha23** [comment]
Hi @rafael2k, thanks for this. My input yuv is 420p 8bit, encoded with vvenc to get a .266 bitstream, then decoding even with the VTM decoder software to a yuv file and extracting the frames with ffmpeg gave wrong results. Eg. instead of extracting the encoded 8 frames, ffmpeg extracted 16 frames, giving the fixel format yuv420p10le as noted by you extracted the correct number of frames. So this is the default pixel format they are encoding the input yuv to.. I think?

**Comment by adamjw24** [comment]
Dear moha23,
so the output format of the decoder is defined by the bitstream. For 8 bits input, the decoder output is yuv420p, for 10 bit input, the decoder output is yuv420p10le. The idea behind that is, that the decoder just translates the bitstream to its exact representation as a video. Any reformatting would be a post-processing step, i.e. not part of the actual decoder.
For the VVenC encoding, the default is to encode everything with 10-bit internal bit-depth. For the expert app this can be set using the InternalBitDepth parameter. For the simple app, we will an appropriate option for a new release coming up next week.
Hope this helps resolve the confusion.

**Comment by moha23** [comment]
makes sense, thank you for clarifying!
