### ISSUE TITLE
Decoding into a color desynced video

### ISSUE THREAD

**Issue by nate-moo** [fraunhoferhhi/vvdec#59]
Each color is desynced and displayed at a different time causing a scrolling picture with frame edges falling over into the next frame

OS: Windows 10 - WSL 2
CPU: Ryzen 7 3700x
GPU Nvidia RTX 3060
Ram: 32gb

Original:
![mpv-shot0005](https://user-images.githubusercontent.com/40650681/128906639-29f600df-7e94-4baa-852c-6b1249159ada.jpg)
Decoded:
![mpv-shot0001](https://user-images.githubusercontent.com/40650681/128906455-de3bbbc5-610e-468a-a0c3-e5b505088f19.jpg)

**Comment by adamjw24** [comment]
I'm pretty sure the problem lies with your encoding. Did you try encoding a .y4m file with VTM or VVenC? Neither understands the .y4m syntax and would treat the header as video bits, thus the content shift. The decoder just reproduces what is contained in the bitstream.

Please make sure you encode a raw yuv without a Y4M header.

**Comment by nate-moo** [comment]
Sorry for the late reply, I don't believe I encoded to a y4m, I encoded to a .h266 file using vvenc and decoded to a .yuv file using vvdec

**Comment by adamjw24** [comment]
Could you post the whole chain of calls you used to encode and decode a video?

Best regards,
Adam
