### ISSUE TITLE
Y4M locked at 50fps output

### ISSUE THREAD

**Issue by baxxtor** [fraunhoferhhi/vvdec#66]
Would is be possible to add a feature that allows the FPS adjustment of the Y4M output mode (such as 30, 25, 24 FPS etc.).  Currently, Y4M output is locked to 50fps.  

Thank you for your consideration.

**Comment by lehmann-c** [comment]
vvdec uses the correct fps for Y4M only when it´s available in the bitstream.
This information is only available, if the HRD is set properly (numUnitsinTick and timescale). 
Otherwise it uses the default framerate 50.

The yuv player can be forced to play at a particular framerate: ffplay or the mpv player are using --fps=60
Otherwise the framerate could also be changed, by adjusting the YUV4MPEG2 Header in 4YM file.
An other  approach would be the usage of mp4 files (by using e.g. GPAC).

**Comment by lehmann-c** [comment]
I´m happy to announce that the upcoming vvenc version will probably be able to write the framerate into the bitstream.
So in the next release this information would always be available and the fps is signalized correctly.

**Comment by baxxtor** [comment]
Thank you.  I appreciate the support and feature request.

**Comment by adamjw24** [comment]
VVenC 1.3 supports proper signaling of timing information, which the decoder should now properly include into the Y4M header. Closing.
