### ISSUE TITLE
Android Build

### ISSUE THREAD

**Issue by baxxtor** [fraunhoferhhi/vvdec#88]
This is more of a question then an issue.  How would one use make to build the Android app?  After I generate the exectables using 'make install-release' all that is built is vvdec.exe for Windows.

Any help would be appreciated.

**Comment by adamjw24** [comment]
You cannot build an App for Android. You need to create an App for Android that uses VVdeC as a dependency. Than you need to create an Android libvvdec.so, and ship it together with that App. Any application using a pre-5.0 FFmpeg can compiled using the https://github.com/tbiat/FFmpeg as dependency, instead of upstream. When enabling `--enable-libvvdec` for that FFmpeg, any App linked against it should support VVC.

**Comment by baxxtor** [comment]
Thank You.  This is excellent information and makes sense.  I was not aware pre-5 FFmpeg has optional vvdec support.
